apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: go-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: go-deploy
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 50 # Adjust based on your application's requirements
