coverage:
  status:
    project:
      default:
        target: auto
        threshold: 0%
        base: auto
    patch:
      default:
        target: auto
        threshold: 0%
        base: auto
  notify:
    after_n_builds: 1
    wait_for_ci: true
comment:
  layout: "reach, diff, flags, files"
  behavior: default
