name: Go CI Workflow

# Trigger the workflow on push or pull request
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  # First stage: Build
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    # Debug step: Print current directory and files
    - name: Print directory structure (for debugging)
      run: |
        pwd
        ls -R  # Recursively list all files to confirm directory structure

    - name: Build Go project
      run: |
        cd src/go-microservices  # Navigate to the correct directory
        ls  # List files in this directory for verification
        go build -o main  # Build the project and output the binary as 'main'

